# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170330_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
